### ISSUE TITLE
Roadmap for the first beta build

### ISSUE THREAD

**Issue by Zarthus** [Zarthus/irc-games-bot#1]
- [ ] docs
  - [ ] API keys
  - [ ] Configuration
  - [x] Experience
  - [ ] Making a game
  - [x] Mechanisms
  - [x] Replay Tags
  - [x] Replays
  - [x] Requirements
  - [ ] Starting a new game
  - [x] Support
  - [x] Syntax Help
- [ ] database
  - [x] migrations 
  - [ ] integrated with the game manager
- [ ] games
  - [ ] A test game
- [ ] game manager
  - [ ] allow inclusion of mechanisms
  - [ ] waiting period
  - [ ] load the game core
  - [ ] cleanup on game end
- [ ] command help
  - [ ] extensive gist of all commands
  - [ ] `!help <command>` -- syntax help about command
  - [ ] `!info <command>` -- information about command
  - [ ] Allow getting help items via it's API for `!command help`
- [ ] mechanims
  - [ ] dynamically loading
- [ ] replays
  - [x] storing
  - [ ] getting
  - [x] tests
- [ ] tests
  - [ ] parser for games to ensure the required components exist
  - [x] Travis CI
  - [x] RSpec tests
- [x] Rake and Bundler utilities
- [ ] web
  - [x] display dosc
  - [x] display readme
  - [ ] get replays
